spring:
  application:
    name: affable-bean-backend
  datasource:
    url: jdbc:mysql://localhost:3306/affablebean
    username: root
    password: Ayechanmyaemoe1783
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8090
